using System.Collections.Immutable;
using System.Linq;
using System.Text;
using System.Threading;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace MapperPillow.Generator;

/// <summary>
/// Milestone 1 of the MapperPillow generator: prove the discovery pipeline.
///
/// It scans for <c>source.MapTo&lt;TDestination&gt;()</c> invocations, resolves the
/// (source, destination) type pair via the semantic model, and emits a summary of
/// what it found. Milestone 2 turns each discovered call site into a compile-time
/// interceptor (via <c>SemanticModel.GetInterceptableLocation</c>) so the runtime
/// reflection fallback is never hit.
/// </summary>
[Generator]
public sealed class MapToDiscoveryGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var mappings = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: static (node, _) => IsCandidateMapToCall(node),
                transform: static (ctx, ct) => GetMapping(ctx, ct))
            .Where(static m => m is not null)
            .Select(static (m, _) => m!.Value)
            .Collect();

        context.RegisterSourceOutput(mappings, static (spc, items) => Emit(spc, items));
    }

    // Cheap, allocation-free syntactic gate: `<expr>.MapTo<...>(...)`.
    private static bool IsCandidateMapToCall(SyntaxNode node) =>
        node is InvocationExpressionSyntax
        {
            Expression: MemberAccessExpressionSyntax
            {
                Name: GenericNameSyntax { Identifier.ValueText: "MapTo" }
            }
        };

    private static (string Source, string Destination)? GetMapping(
        GeneratorSyntaxContext ctx, CancellationToken ct)
    {
        var invocation = (InvocationExpressionSyntax)ctx.Node;
        var memberAccess = (MemberAccessExpressionSyntax)invocation.Expression;
        var generic = (GenericNameSyntax)memberAccess.Name;

        if (generic.TypeArgumentList.Arguments.Count != 1)
        {
            return null;
        }

        var destSymbol = ctx.SemanticModel.GetTypeInfo(generic.TypeArgumentList.Arguments[0], ct).Type;
        var srcSymbol = ctx.SemanticModel.GetTypeInfo(memberAccess.Expression, ct).Type;

        if (destSymbol is null || srcSymbol is null)
        {
            return null;
        }

        return (
            srcSymbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat),
            destSymbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat));
    }

    private static void Emit(SourceProductionContext spc, ImmutableArray<(string Source, string Destination)> mappings)
    {
        var distinct = mappings
            .Distinct()
            .OrderBy(m => m.Source, System.StringComparer.Ordinal)
            .ThenBy(m => m.Destination, System.StringComparer.Ordinal)
            .ToArray();

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("// MapperPillow — discovered mappings (generator milestone 1).");
        sb.AppendLine("// Milestone 2 replaces these call sites with compile-time interceptors.");
        sb.AppendLine($"// Count: {distinct.Length}");
        sb.AppendLine("namespace MapperPillow.Generated");
        sb.AppendLine("{");
        foreach (var m in distinct)
        {
            sb.AppendLine($"    //   {m.Source} -> {m.Destination}");
        }
        sb.AppendLine("    internal static class DiscoveredMappings");
        sb.AppendLine("    {");
        sb.AppendLine($"        public const int Count = {distinct.Length};");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        spc.AddSource("MapperPillow.DiscoveredMappings.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
    }
}
